service: serverless-bolt-js
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_CLIENT_ID: ${env:SLACK_CLIENT_ID}
    SLACK_CLIENT_SECRET: ${env:SLACK_CLIENT_SECRET}
    SLACK_STATE_SECRET: ${env:SLACK_STATE_SECRET}
functions:
  slack:
    handler: dist/app.handler
    events:
      - http:
          path: slack/events
          method: post
plugins:
  - serverless-offline
  - serverless-dynamodb-local